/* eslint-disable no-unused-vars */
let CertificationsData = [
    {
      name: "Meta Front-End Developer",
      authority: 'Coursera',
      date: "Oct 2024",
      img: "https://s3.amazonaws.com/coursera_assets/meta_images/generated/CERTIFICATE_LANDING_PAGE/CERTIFICATE_LANDING_PAGE~NPOCFF1IZ9PR/CERTIFICATE_LANDING_PAGE~NPOCFF1IZ9PR.jpeg",
      link: "https://www.coursera.org/account/accomplishments/professional-cert/NPOCFF1IZ9PR",
      category: ["all", "coursera"],
    },
    {
      name: "JavaScript: ES6",
      authority: "Information Technology Institute",
      date: "Oct 2024",
      img: "https://i.imgur.com/05NP1Xc.png",
      link: "    https://drive.google.com/file/d/1pnkVC14SVO-0jWc0xj_6CVVLKQT3-bj3/view?usp=sharing",
      category: ["all", "iti"],
    },
    {
      name: "TypeScript Fundamentals",
      authority: "Information Technology Institute",
      date: "Oct 2024",
      img: "https://i.imgur.com/8yHuEcW.png",
      link: "https://drive.google.com/file/d/1dHf-5lyZJTCNzEjoJRAGirP5N3pMU9wo/view?usp=sharing",
      category: ["all", "iti"],
    },
    {
      name: "CSS (Basic) Certificate",
      authority: "HackerRank",
      date: "2 Sep 2024",
      img: "https://i.imgur.com/AjXzstq.png",
      link: "https://www.hackerrank.com/certificates/3d9f824a40b4",
      category: ["all", "hackerrank"],
    },
    {
      name: "Software Engineer Certificate",
      authority: "HackerRank",
      date: "3 Sep 2024",
      img: "https://i.imgur.com/kKIWGJU.png",
      link: "https://www.hackerrank.com/certificates/c048672d365b",
      category: ["all", "hackerrank"],
    },
    {
      name: "JavaScript Basic Certificate",
      authority: "HackerRank",
      date: "Sep 2024",
      img: "https://i.imgur.com/uLzFrg1.png",
      link: "https://www.hackerrank.com/certificates/00ba13273da2",
      category: ["all", "hackerrank"],
    },
    {
      name: "Introduction to JavaScript",
      authority: "ITI",
      date: "May 2024",
      img: "https://i.imgur.com/wBUbTH6.png",
      link: "https://drive.google.com/file/d/1c92aqY932Y2iznrRZoEf_ZasUGevR5o1/view?usp=sharing",
      category: ["all", "iti"],
    },
    {
      name: "Intro to HTML, CSS",
      authority: "ITI",
      date: "Apr 2024",
      img: "https://i.imgur.com/qjCMV4s.png",
      link: "https://drive.google.com/file/d/1lm2nS1iCo7CO4Ja9eTDa_lDmmX854uND/view?usp=sharing",
      category: ["all", "iti"],
    },
    {
      name: "SQL Intermediate",
      authority: "HackerRank",
      date: "Apr 2022",
      img: "https://i.imgur.com/B2ILogn.png",
      link: "https://www.hackerrank.com/certificates/7a5e653b4263",
      category: ["all", "hackerrank"],
    },
    {
      name: "Data Analysis Challenger Track",
      authority: "Udacity",
      date: "Feb 2022",
      img: "https://i.imgur.com/aMcRTaf.png",
      link: "https://drive.google.com/file/d/14EPD-f6H2WBOn9t3hs3FrjVMNm-3XqQY/view?usp=sharing",
      category: ["all", "udacity"],
    },
    {
      name: "Web Developer Intern",
      authority: "ITI",
      date: "Aug to Sep 2024",
      img: "https://i.imgur.com/xs63ckN.png",
      link: "https://drive.google.com/file/d/1vh2weLv07nrL7abloGveXdr6dWSMPDMo/view?usp=sharing",
      category: ["all", "internships"],
    },
    {
      name: "Mobile Developer Intern",
      authority: "CodeAlpha",
      date: "March 2024",
      img: "https://i.imgur.com/Xy5n7gk.png",
      link: "https://drive.google.com/file/d/13L6sFGGOVdIirJSkIO6o8lE-oXVmbiJk/view?usp=sharing",
      category: ["all", "internships"],
    },
    {
      name: "Business Analytics Intern",
      authority: "Sparks Foundation",
      date: "May to Jun 2022",
      img: "https://i.imgur.com/mDTxCEo.png",
      link: "https://drive.google.com/file/d/1_fv57tUHZocWmnSepaolnpP0O-mgZGVG/view?usp=sharing",
      category: ["all", "internships"],
    },
  ];
  
  export default CertificationsData;
  